modLoader="javafml"
loaderVersion="[4,)"                # NeoForge FML
license="MIT"
issueTrackerURL=""

[[mods]]
modId="${file.mod_id}"
version="${file.jarVersion}"
displayName="Nether Portal No More"
authors="CyberDay1"
description='''
Prevents Nether portal creation.
'''

[[mixins]] # keep or remove if unused
config=""

[[dependencies.${file.mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${file.mod_id}]]
modId="minecraft"
type="required"
versionRange="[${mc_version}]"
ordering="NONE"
side="BOTH"
