modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="netherportalnomore"
version="1.0.0"
displayName="Nether Portal No More"
authors="CyberDay1"
description='''
Prevents Nether portals from being lit by igniters (flint-and-steel, fire charges, etc).
'''

[[dependencies.netherportalnomore]]
modId="neoforge"
type="required"
versionRange="[21.1.209,)"
ordering="NONE"
side="BOTH"

[[dependencies.netherportalnomore]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
